{
    "name": "Aduana - Operaciones y Pedimentos",
    "version": "18.0.1.5.0",
    "category": "CRM",
    "summary": "Gestión de operaciones aduanales y pedimentos desde CRM",
    "depends": ["crm", "mail", "base", "contacts","account"],
    "data": [
        "data/aduana_layout_registro_tipo_data.xml",
        "security/aduana_groups.xml",
        "security/ir.model.access.csv",
        "views/mx_ped_operacion_views.xml",
        "views/aduana_catalogos_views.xml",
        "views/aduana_layout_tecnico_views.xml",
        "views/aduana_pedimento_views.xml",
        "views/aduana_crm_lead_bridge_views.xml",
        "views/res_partner_views.xml",
        "views/mx_ped_clave_views.xml",
        "views/mx_ped_aduana_seccion_views.xml",
        "views/mx_ped_fraccion_views.xml",
        "views/mx_ped_tipo_contenedor_views.xml",
        "views/mx_ped_numero_control_views.xml",
        "views/mx_ped_layout_views.xml",
        "views/crm_lead_views.xml",
        "views/account_move_views.xml",
        "views/mx_only_cleanup_views.xml",
    ],
    "license": "LGPL-3",
    "application": False,
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "modulo_aduana_odoo/static/src/scss/aduana_theme.scss",
        ],
    },
}
