{
    "name": "Aduanex",
    "version": "18.0.1.9.0",
    "category": "CRM",
    "summary": "Gestión de operaciones aduanales y pedimentos desde CRM",
    "depends": ["crm", "mail", "base", "contacts", "account"],
    "data": [
        "data/mail_template_portal_invite.xml",
        "data/aduana_layout_registro_tipo_data.xml",
        "data/mx_ped_tipo_movimiento_data.xml",
        "data/mx_ped_layout_voce_data.xml",
        "data/mx_ped_rulepack_data.xml",
        "data/mx_ped_rulepack_field_rules.xml",
        "security/aduana_groups.xml",
        "security/ir.model.access.csv",
        "views/mx_ped_consolidado_views.xml",
        "views/mx_ped_operacion_views.xml",
        "views/mx_ped_partida_factura_wizard_views.xml",
        "views/mx_ped_validacion_wizard_views.xml",
        "views/mx_ped_desistimiento_wizard_views.xml",
        "views/mx_cove_views.xml",
        "views/mx_doda_views.xml",
        "views/crm_lead_views.xml",
        "views/mx_ped_clave_views.xml",
        "views/aduana_catalogos_views.xml",
        "views/aduana_layout_tecnico_views.xml",
        "views/aduana_pedimento_views.xml",
        "views/aduana_crm_lead_bridge_views.xml",
        "views/res_partner_views.xml",
        "views/mx_ped_rulepack_views.xml",
        "views/mx_ped_aduana_seccion_views.xml",
        "views/mx_tigie_maestra_views.xml",
        "views/mx_ped_fraccion_views.xml",
        "views/mx_ped_regulatorio_views.xml",
        "views/mx_ped_identificador_views.xml",
        "views/mx_ped_credencial_ws_views.xml",
        "views/mx_anam_gafete_views.xml",
        "views/mx_ped_tipo_movimiento_views.xml",
        "views/mx_ped_tipo_contenedor_views.xml",
        "views/mx_ped_estructura_regla_views.xml",
        "views/mx_ped_numero_control_views.xml",
        "views/mx_ped_layout_views.xml",
        "views/account_move_views.xml",
        "views/mx_only_cleanup_views.xml",
        "views/aduana_dashboard_views.xml",
        "views/aduana_setup_wizard_views.xml",
    ],
    "external_dependencies": {
        "python": ["requests", "PyPDF2", "reportlab", "cryptography", "zeep"],
    },
    "license": "LGPL-3",
    "application": False,
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "modulo_aduana_odoo/static/src/scss/aduana_theme.scss",
            "modulo_aduana_odoo/static/src/js/qr_camera_scanner.esm.js",
            "modulo_aduana_odoo/static/src/xml/qr_camera_scanner.xml",
        ],
    },
}
