from . import crm_lead
from . import mx_ped_operacion
from . import mx_ped_partida
from . import mx_ped_documento
from . import mx_ped_evento
from . import mx_ped_layout
from . import mx_ped_registro
from . import res_partner
from . import mx_ped_clave
