from . import crm_lead
from . import res_partner
from . import mx_ped_operacion
from . import mx_ped_partida
from . import mx_ped_documento
from . import mx_ped_evento
from . import mx_ped_layout
from . import mx_ped_registro
from . import mx_ped_clave
from . import mx_ped_aduana_seccion
from . import mx_ped_fraccion
from . import mx_ped_regulatorio
from . import mx_ped_forma_pago
from . import mx_ped_tipo_movimiento
from . import mx_ped_tipo_contenedor
from . import mx_ped_numero_control
from . import mx_ped_estructura_regla
from . import mx_ped_rulepack
from . import mx_wa_session
from . import account_move
from . import aduana_catalogos
from . import aduana_pedimento
from . import aduana_layout_tecnico
